# Generated by Django 3.1.5 on 2021-01-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudApi', '0002_userimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimages',
            name='image',
            field=models.ImageField(upload_to='media/uploads'),
        ),
    ]
