# Generated by Django 3.1.5 on 2021-01-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudApi', '0003_auto_20210127_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimages',
            name='image',
            field=models.FileField(upload_to='media/uploads'),
        ),
    ]
