# Generated by Django 3.1.5 on 2021-01-28 11:41

import crudApi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudApi', '0004_auto_20210127_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimages',
            name='image',
            field=models.ImageField(upload_to=crudApi.models.upload_to),
        ),
    ]
